type=item
matchItems=crossbow
model=./soul_hunter
model.crossbow_arrow=soul_hunter_arrow
model.crossbow_firework=soul_hunter_firework
model.crossbow_pulling_0=soul_hunter_pulling_0
model.crossbow_pulling_1=soul_hunter_pulling_1
model.crossbow_pulling_2=soul_hunter_pulling_2
nbt.display.Name=The Soul Hunter
