type=item
matchItems=netherite_pickaxe
model=optifine/cit/tools/pickaxe_fortunate
texture=pickaxe_fortunate
nbt.display.Name=iregex:.*(Fortunate boi|Lil Fortune|The Money Drill).*
enchantments=fortune