type=item
matchItems=netherite_pickaxe
model=optifine/cit/tools/pickaxe_silky
texture=pickaxe
nbt.display.Name=iregex:.*(Silky boi|The Silky Drill|Smooth like butter|Lil Silky).*
enchantments=silk_touch