type=item
matchItems=netherite_shovel
model=optifine/cit/tools/shovel
texture=shovel
nbt.display.Name=iregex:.*(Speedy boi|The Shiny Spoon|The Speedy Scoop|The Earth Scooper|Sir Scoopy-doo).*
enchantments=efficiency